// <auto-generated />
namespace PricesEntitiesModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class replaceditemwithpricesinstoreentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(replaceditemwithpricesinstoreentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201609101324473_replaced item with prices in store entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
